# Generated by Django 6.0.3 on 2026-05-05 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PcComponents', '0002_contacto_productos_foreign_key'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacto',
            old_name='message',
            new_name='mensaje',
        ),
        migrations.RemoveField(
            model_name='productos',
            name='foreign_key',
        ),
        migrations.AddField(
            model_name='productos',
            name='comentario',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='PcComponents.contacto'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
