# Generated by Django 6.0.3 on 2026-05-06 00:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PcComponents', '0003_rename_message_contacto_mensaje_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productos',
            name='comentario',
        ),
        migrations.AddField(
            model_name='contacto',
            name='productos',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='PcComponents.productos'),
        ),
    ]
